import { Question } from "../types";

export const initialQuestions: Question[] = [
  {
    questionId: "seed-sp5-2025-q1",
    examBody: "IFOA",
    subject: "SP", // Will match "SP" subject card
    chapter: "Asset Liability Matching",
    topic: "Immunisation Theory",
    difficulty: "Hard",
    marks: 15,
    commandWord: "Discuss",
    question: "An insurance company has long-term liabilities with average duration of 18 years. Explain how Redington's multi-period immunisation strategy can decrease mismatching risk, and discuss the main practical limitations of this theory in high-inflation environments.\n\ni) State Redington's three core mathematical conditions for immunization.\nii) Outline how unexpected inflation shifts the asset-liability duration relationship.",
    rephrasedQuestion: "A life insurer holds liabilities stretching out 18 years on average. Analyze how multi-period financial matching guards against interest fluctuation, and discuss the real-world boundaries of the model when price levels are escalating rapidly.\n\ni) State the fundamental three mathematical terms of the Redington strategy.\nii) Outline the effect of swift inflation rates upon asset and liability durations.",
    officialAnswer: "Redington's conditions require:\n1. The present value of assets equals the present value of liabilities: PV(A) = PV(L).\n2. The sensitivity of assets is equal to the sensitivity of liabilities: dA/dy = dL/dy (equal durations).\n3. The convexity of assets is greater than the convexity of liabilities: d^2A/dy^2 > d^2L/dy^2.\n\nPractical limitations are that the yield curve shifts are rarely parallel, transactions costs prevent continuous rebalancing, inflation causes liability values and cashflows to escalate unpredictably if benefits are index-linked.",
    markScheme: "- 3 marks for stating Redington's conditions accurately (1 mark each).\n- 6 marks for explanation of multi-period matching and liability duration shifts under inflation.\n- 6 marks for detailed analysis of practical roadblocks, including yield curve non-parallelism and high transaction friction.",
    examinerReport: "Overall, candidates performed reasonably well on part (i), but struggled to apply the immunization criteria to high-inflation environments. Many candidates failed to mention that convexities must be evaluated on an index-linked basis if inflation targets are embedded in the liabilities. Successful answers highlighted transactional friction.",
    aiSolution: "### Detailed Explanatory Actuarial Guide\n\nTo immunise a set of interest-rate sensitive cashflows under Redington's model, the asset manager must construct a portfolio such that any tiny, parallel shift in the yield curve results in the assets outperforming the liabilities.\n\n#### Core Equations\nRedington's conditions are mathematically stated as:\n$$\\sum A_t (1+y)^{-t} = \\sum L_t (1+y)^{-t}$$\n$$\\sum t A_t (1+y)^{-t-1} = \\sum t L_t (1+y)^{-t-1}$$\n$$\\sum t^2 A_t (1+y)^{-t-2} > \\sum t^2 L_t (1+y)^{-t-2}$$\n\n#### Key Concept: Inflation Mismatching\nWhen inflation arises, liabilities indexed to retail prices escalate. Unless assets are strictly held in index-linked sovereign bonds, a duration mismatch immediately opens up.",
    keyPoints: "• Durations must match perfectly at the present yield level.\n• Convexity of assets must strictly exceed that of liabilities.\n• Parallel yield curve shift is a highly restrictive theoretical assumption.",
    commonMistakes: "• Students confusing duration (first derivative) with convexity (second derivative).\n• Forgetting that liabilities indexation requires real (inflation-adjusted) matching assets.",
    source: "IFOA SP5 April 2025 Paper",
    uploadDate: "2026-06-15T12:00:00Z",
    confidenceScore: 98,
    status: "approved",
    term: "Apr 2025"
  },
  {
    questionId: "seed-cp1-2025-q2",
    examBody: "IFOA",
    subject: "CP1",
    chapter: "Capital Management",
    topic: "Solvency Capital Requirement",
    difficulty: "Medium",
    marks: 10,
    commandWord: "Explain",
    question: "A medium-sized general insurance underwriter is considering moving from the Standard Formula to a proprietary Internal Model under Solvency II. Explain the primary risks, rewards, and necessary supervisory checks for adopting an internal model.",
    rephrasedQuestion: "A mid-sized property-casualty carrier is evaluating switching from the regulated Standard Formula to a custom Internal Model under Solvency II. Describe the primary drawbacks, opportunities, and regulatory sign-offs required to successfully deploy this custom model.",
    officialAnswer: "Rewards: Internal models reflect the actual risk profile of the firm more accurately, potentially lowering the Solvency Capital Requirement (SCR) by eliminating standard conservative assumptions. It enhances risk awareness throughout the firm. Risks: Highly expensive to design, calibrate, and secure supervisory approval. Subject to model risks and data availability. Supervisor checks: Must pass the 'Use Test' (proving senior management relies on the model), statistical quality standards, and validation assessments.",
    markScheme: "- 3 marks for outlining benefits (custom fit, capital optimization).\n- 3 marks for outlining costs and model risk downsides.\n- 4 marks for supervisors criteria (Use Test, validation methodology, documentation quality).",
    examinerReport: "Most scripts showed solid coverage of Solvency II principles. A key differentiator was the level of depth given on the 'Use Test'. Candidates who gave real business examples of why the board would use the model in day-to-day capital allocation scored maximum marks.",
    aiSolution: "### Explanation under the Solvency II Directive\n\nAdopting an internal model means replacing generic risk coefficients with the firm's empirical distributions. For a property underwriter with unique localized risks, this can unlock significant capital relief.\n\n#### Supervisory 'Use Test' requirements:\n1. **Integration**: The model cannot be a back-office tool; it must drive strategic reinsurance purchase, product pricing, and risk appetite limits.\n2. **Validation**: Independent actuarial sign-off is required with clear stress-tests.",
    keyPoints: "• The 'Use Test' is the single most critical criterion for supervisory sign-off.\n• Diversification benefits are modeled explicitly rather than via correlation matrices.",
    commonMistakes: "• Writing generic comments about insurance risk without detailing statutory standard formulas vs. internal models.\n• Failing to mention validation.",
    source: "IFOA CP1 November 2025 Paper",
    uploadDate: "2026-06-16T10:00:00Z",
    confidenceScore: 94,
    status: "approved",
    term: "Nov 2025"
  },
  {
    questionId: "seed-cm1-2024-q3",
    examBody: "IAI",
    subject: "CM1",
    chapter: "Life Tables & Annuities",
    topic: "Annuity Valuation",
    difficulty: "Easy",
    marks: 8,
    commandWord: "Calculate",
    question: "An individual aged 60 purchases a single-premium life annuity paying 50,000 INR per annum in advance. Using the AM92 Ultimate mortality table at 4% per annum interest, calculate the single net premium required.",
    rephrasedQuestion: "A retiree at sixty buys an immediate life annuity that pays 50,000 INR annually at the start of each year. Calculate the initial net premium needed utilizing the AM92 mortality framework at a constant 4% discount rate.",
    officialAnswer: "The net single premium is given by: Premium = 50,000 * ä_60\nUsing AM92 Ultimate values at 4%:\nä_60 = 1 + a_60, or directly from tables where ä_60 = 14.821 (dummy value matched to AM92 table style).\nPremium = 50,000 * 14.821 = 741,050 INR.",
    markScheme: "- 2 marks for stating the correct actuarial expression: 50,000 * ä_60.\n- 3 marks for looking up or deriving the correct life annuity value.\n- 3 marks for correct calculation of final premium value.",
    examinerReport: "This question was well answered by nearly all candidates. A few failed to calculate payments 'in advance' and mistakenly valued the annuity 'in arrears' (using a_60 instead of ä_60), losing 3 marks. Double check whether payments are at the start or end of the year.",
    aiSolution: "### Mathematical Derivation of Lifetime Annuity\n\nThe premium for a temporary or life annuity in advance is represented as:\n$$\\ddot{a}_x = \\sum_{t=0}^{\\infty} v^t \\,_tp_x$$\n\nSubstituting $x = 60$, $v = 1/1.04$ and matching surviving probabilities from AM92:\nPremium $= 50,000 \\times 14.821 = 741,050$ INR.",
    keyPoints: "• 'In advance' indicates an annuity-due (ä_x).\n• Premium must be calculated net of expenses unless explicit loadings are requested.",
    commonMistakes: "• Confusing annuity in advance (ä_p) with annuity in arrears (a_p).\n• Using incorrect interest rate percentages from standard tables.",
    source: "IAI CM1 November 2024 Paper",
    uploadDate: "2026-06-16T11:00:00Z",
    confidenceScore: 99,
    status: "approved",
    term: "Nov 2024"
  },
  {
    questionId: "seed-cs2-2025-q4",
    examBody: "IAI",
    subject: "CS2",
    chapter: "Stochastic Processes",
    topic: "Markov Chains",
    difficulty: "Hard",
    marks: 12,
    commandWord: "Derive",
    question: "A simple No-Claims Discount (NCD) system has three levels: 0%, 20%, and 40%. Claims occur according to a Poisson process with parameter lambda. Derive the transition probability matrix and find the long-term stationary distribution.",
    rephrasedQuestion: "A basic automotive discount reward mechanism has three classes: 0%, 20%, and 40%. Accident records follow a Poisson rate process of lambda. Derive the formula for transition likelihoods and determine the final steady-state occupancy probabilities.",
    officialAnswer: "If a claim occurs, the policyholder goes down one level (or stays at 0%). If no claim occurs, they go up one level (or stay at 40%). Let probability of no claim be p = e^-lambda.\nTransition Matrix P:\n[[1-p, p, 0],\n [1-p, 0, p],\n [0, 1-p, p]]\nSolving stationary state pi * P = pi, yields dependencies where pi_0 = 1 - p, pi_1 = p(1-p), and pi_2 = p^2.",
    markScheme: "- 4 marks for deriving the 3x3 transition matrix correctly using p = e^-lambda.\n- 5 marks for setting up steady state equations pi * P = pi.\n- 3 marks for solving and expressing pi in terms of p.",
    examinerReport: "This question was split. Strong mathematical thinkers scored full marks easily, whereas several candidates wrote incorrect transition probabilities, especially for the boundary states (0% and 40%). The assumption of Poisson rate parameter was handled correctly.",
    aiSolution: "### Detailed Markov Chain stationary analysis\n\nLet the state space represent NCD discount classes: $S = \\{0, 1, 2\\}$ corresponding to $0\\%, 20\\%$, and $40\\%$ discounts.\n\nThe probability of zero claims during any single policy year is given by $p = P(N=0) = e^{-\\lambda}$.\n\nThe probability of at least one claim is $q = 1 - p = 1 - e^{-\\lambda}$.\n\n#### Solving Pi relations\nWe write system equations:\n$$\\pi_0 = q\\pi_0 + q\\pi_1$$\n$$\\pi_1 = p\\pi_0 + q\\pi_2$$\n$$\\pi_2 = p\\pi_1 + p\\pi_2$$",
    keyPoints: "• The sum of stationary probabilities must always equal 1.\n• Boundary states absorb transition spills when no claims occur at maximum level.",
    commonMistakes: "• Incorrectly placing transition probabilities in columns rather than rows.\n• Overlooking the fact that claims drop the user by a discrete, single level.",
    source: "IAI CS2 April 2025 Paper",
    uploadDate: "2026-06-14T09:30:00Z",
    confidenceScore: 92,
    status: "approved",
    term: "Apr 2025"
  }
];
